[pytest]
testpaths = tests
env =
    NOTIFY_ENVIRONMENT=test
    MMG_API_KEY=mmg-secret-key
    FIRETEXT_API_KEY=Firetext
    NOTIFICATION_QUEUE_PREFIX=testing
    REDIS_ENABLED=0
    API_HOST_NAME=http://localhost:6011
    ADMIN_BASE_URL=http://localhost:6012
addopts = -p no:warnings
xfail_strict = true
