"""empty message

Revision ID: 0002_add_content_char_count
Revises: 0001_restart_migrations
Create Date: 2016-04-15 12:12:46.383782

"""

# revision identifiers, used by Alembic.
revision = "0002_add_content_char_count"
down_revision = "0001_restart_migrations"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("content_char_count", sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "content_char_count")
    ### end Alembic commands ###
