"""empty message

Revision ID: 0005_add_job_details
Revises: 0004_create_jobs
Create Date: 2016-01-15 15:57:38.022562

"""

# revision identifiers, used by Alembic.
revision = '0005_add_job_details'
down_revision = '0004_create_jobs'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('bucket_name', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('file_name', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'file_name')
    op.drop_column('jobs', 'bucket_name')
    ### end Alembic commands ###
