"""empty message

Revision ID: 0009_unique_service_to_key_name
Revises: 0007_change_to_api_keys
Create Date: 2016-01-21 16:14:51.773001

"""

# revision identifiers, used by Alembic.
revision = '0009_unique_service_to_key_name'
down_revision = '0008_add_verify_codes'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_service_to_key_name', 'api_key', ['service_id', 'name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_service_to_key_name', 'api_key', type_='unique')
    ### end Alembic commands ###
