"""empty message

Revision ID: 0010_add_queue_name_to_service
Revises: 0009_unique_service_to_key_name
Create Date: 2016-01-27 13:53:34.717916

"""

# revision identifiers, used by Alembic.

revision = '0010_add_queue_name_to_service'
down_revision = '0009_unique_service_to_key_name'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('queue_name', postgresql.UUID(as_uuid=True), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'queue_name')
    ### end Alembic commands ###
