"""empty message

Revision ID: 0012_add_status_to_job
Revises: 0011_uuid_service_id
Create Date: 2016-02-02 11:25:34.402864

"""

# revision identifiers, used by Alembic.
revision = '0012_add_status_to_job'
down_revision = '0011_uuid_service_id'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    job_status_types = sa.Enum('pending', 'in progress', 'finished', name='job_status_types')
    job_status_types.create(op.get_bind())
    op.add_column('jobs', sa.Column('status', job_status_types, nullable=True))
    op.get_bind()
    op.execute("update jobs set status='pending'")
    op.alter_column('jobs', 'status', nullable=False)


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    op.execute('DROP TYPE job_status_types')
    ### end Alembic commands ###
