"""empty message

Revision ID: 0014_job_id_nullable
Revises: 0013_add_notifications
Create Date: 2016-02-10 10:57:39.414061

"""

# revision identifiers, used by Alembic.
revision = '0014_job_id_nullable'
down_revision = '0013_add_notifications'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'job_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'job_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    ### end Alembic commands ###
