"""empty message

Revision ID: 0015_add_permissions
Revises: 0014_job_id_nullable
Create Date: 2016-02-19 14:16:59.359493

"""

# revision identifiers, used by Alembic.
revision = '0015_add_permissions'
down_revision = '0014_job_id_nullable'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    ### end Alembic commands ###
