"""empty message

Revision ID: 0016_reply_to_email
Revises: 0015_fix_template_data
Create Date: 2016-05-17 09:59:49.032865

"""

# revision identifiers, used by Alembic.
revision = '0016_reply_to_email'
down_revision = '0015_fix_template_data'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('reply_to_email_address', sa.Text(), nullable=True))
    op.add_column('services_history', sa.Column('reply_to_email_address', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_history', 'reply_to_email_address')
    op.drop_column('services', 'reply_to_email_address')
    ### end Alembic commands ###
