"""empty message

Revision ID: 0018_remove_subject_uniqueness
Revises: 0017_add_failure_types
Create Date: 2016-05-18 09:39:22.512042

"""

# revision identifiers, used by Alembic.
revision = '0018_remove_subject_uniqueness'
down_revision = '0017_add_failure_types'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates_subject_key', 'templates', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('templates_subject_key', 'templates', ['subject'])
    ### end Alembic commands ###
