"""empty message

Revision ID: 0023_rename_token
Revises: 0022_add_invite_users
Create Date: 2016-02-24 11:17:14.670874

"""

# revision identifiers, used by Alembic.
revision = '0023_rename_token'
down_revision = '0022_add_invite_users'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invited_users', '_token', new_column_name='token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invited_users', 'token', new_column_name='_token')
    ### end Alembic commands ###
