"""empty message

Revision ID: 0023_drop_token
Revises: 0022_add_invite_users
Create Date: 2016-02-24 13:58:04.440296

"""

# revision identifiers, used by Alembic.
revision = '0023_drop_token'
down_revision = '0022_add_invite_users'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invited_users', '_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invited_users', sa.Column('_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
