"""empty message

Revision ID: 0026_rename_notify_service
Revises: 0025_notify_service_data
Create Date: 2016-06-07 09:51:07.343334

"""

# revision identifiers, used by Alembic.
revision = '0026_rename_notify_service'
down_revision = '0025_notify_service_data'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.get_bind()
    op.execute("update services set name = 'GOV.UK Notify' where id = 'd6aa2c68-a2d9-4437-ab19-3ae8eb202553'")
    op.execute("update services_history set name = 'GOV.UK Notify' where id = 'd6aa2c68-a2d9-4437-ab19-3ae8eb202553'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
