"""empty message

Revision ID: 0029_add_permissions_to_invite
Revises: 0028_add_default_permissions
Create Date: 2016-02-26 16:17:30.612924

"""

# revision identifiers, used by Alembic.
revision = '0029_add_permissions_to_invite'
down_revision = '0028_add_default_permissions'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invited_users', sa.Column('permissions', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invited_users', 'permissions')
    ### end Alembic commands ###
