"""empty message

Revision ID: 0031_store_personalisation
Revises: 0030_service_id_not_null
Create Date: 2016-06-20 10:39:50.892847

"""

# revision identifiers, used by Alembic.
revision = '0031_store_personalisation'
down_revision = '0030_service_id_not_null'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('_personalisation', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', '_personalisation')
    ### end Alembic commands ###
