"""empty message

Revision ID: 0034_job_sent_count
Revises: 0033_correct_permission_enums
Create Date: 2016-03-04 13:44:32.217058

"""

# revision identifiers, used by Alembic.
revision = '0034_job_sent_count'
down_revision = '0033_correct_permission_enums'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('notifications_sent', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'notifications_sent')
    ### end Alembic commands ###
