"""notification_api_key_not_nullable

Revision ID: 0036_notif_key_type_not_null
Revises: 0035_notification_type
Create Date: 2016-07-01 16:01:16.892638

"""

# revision identifiers, used by Alembic.
revision = '0036_notif_key_type_not_null'
down_revision = '0035_notification_type'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("update notifications set key_type = 'normal' where key_type is null")
    op.alter_column('notifications', 'key_type', existing_type=sa.VARCHAR(length=255), nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'key_type', existing_type=sa.VARCHAR(length=255), nullable=True)
    ### end Alembic commands ###
