"""empty message

Revision ID: 0067_service_contact_block
Revises: 0066_add_dvla_provider
Create Date: 2017-02-28 11:23:40.299110

"""

# revision identifiers, used by Alembic.
revision = '0067_service_contact_block'
down_revision = '0066_add_dvla_provider'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('letter_contact_block', sa.Text(), nullable=True))
    op.add_column('services_history', sa.Column('letter_contact_block', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_history', 'letter_contact_block')
    op.drop_column('services', 'letter_contact_block')
    ### end Alembic commands ###
