"""

Revision ID: 0125_remove_unique_constraint
Revises: 0124_add_free_sms_fragment_limit
Create Date: 2017-10-17 16:47:37.826333

"""
from alembic import op
import sqlalchemy as sa

revision = '0125_remove_unique_constraint'
down_revision = '0124_add_free_sms_fragment_limit'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_sms_senders_service_id', table_name='service_sms_senders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_sms_senders_service_id'), table_name='service_sms_senders')
    op.create_index('ix_service_sms_senders_service_id', 'service_sms_senders', ['service_id'], unique=True)
    # ### end Alembic commands ###
