"""

Revision ID: 0137_sms_sender_nullable
Revises: 0136_user_mobile_nullable
Create Date: 2017-11-06 15:44:59.471977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0137_sms_sender_nullable'
down_revision = '0136_user_mobile_nullable'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_statistics')
    op.alter_column('services', 'sms_sender',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=True)
    op.alter_column('services_history', 'sms_sender',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services_history', 'sms_sender',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=False)
    op.alter_column('services', 'sms_sender',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=False)
    op.create_table('notification_statistics',
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('service_id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('emails_requested', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('emails_delivered', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('emails_failed', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('sms_requested', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('sms_delivered', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('sms_failed', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'],
                                            name='notification_statistics_service_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='notification_statistics_pkey'),
                    sa.UniqueConstraint('service_id', 'day', name='uix_service_to_day')
                    )
    # ### end Alembic commands ###
