"""

Revision ID: 0258_service_postage_nullable
Revises: 0257_letter_branding_migration
Create Date: 2019-02-12 11:52:53.139383

"""

import sqlalchemy as sa
from alembic import op

revision = "0258_service_postage_nullable"
down_revision = "0257_letter_branding_migration"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("services_history", "postage", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("services", "postage", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("services_history", "postage", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("services", "postage", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
