"""

Revision ID: 0319_high_volume_service
Revises: 0318_service_contact_list
Create Date: 2020-03-20 08:53:22.624516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0319_high_volume_service'
down_revision = '0318_service_contact_list'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_volume_service',
                    sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.PrimaryKeyConstraint('service_id')
                    )
    op.create_index(op.f('ix_high_volume_service_service_id'), 'high_volume_service', ['service_id'], unique=True)


def downgrade():
    op.drop_index(op.f('ix_high_volume_service_service_id'), table_name='high_volume_service')
    op.drop_table('high_volume_service')
