"""

Revision ID: 0329_purge_broadcast_data
Revises: 0328_international_letters_perm
Create Date: 2020-09-07 16:00:27.545673

"""
from alembic import op


revision = '0329_purge_broadcast_data'
down_revision = '0328_international_letters_perm'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE broadcast_event, broadcast_message;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
