"""

Revision ID: 0338_add_notes_to_service
Revises: 0337_broadcast_msg_api
Create Date: 2021-01-13 11:50:06.333369

"""

import sqlalchemy as sa
from alembic import op

revision = "0338_add_notes_to_service"
down_revision = "0337_broadcast_msg_api"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("services_history", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services_history", "notes")
    op.drop_column("services", "notes")
    # ### end Alembic commands ###
