"""

Revision ID: 0339_service_billing_details
Revises: 0338_add_notes_to_service
Create Date: 2021-01-20 17:55:46.555460

"""

import sqlalchemy as sa
from alembic import op

revision = "0339_service_billing_details"
down_revision = "0338_add_notes_to_service"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("billing_contact_email_addresses", sa.Text(), nullable=True))
    op.add_column("services", sa.Column("billing_contact_names", sa.Text(), nullable=True))
    op.add_column("services", sa.Column("billing_reference", sa.String(length=255), nullable=True))
    op.add_column("services", sa.Column("purchase_order_number", sa.String(length=255), nullable=True))
    op.add_column("services_history", sa.Column("billing_contact_email_addresses", sa.Text(), nullable=True))
    op.add_column("services_history", sa.Column("billing_contact_names", sa.Text(), nullable=True))
    op.add_column("services_history", sa.Column("billing_reference", sa.String(length=255), nullable=True))
    op.add_column("services_history", sa.Column("purchase_order_number", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services_history", "purchase_order_number")
    op.drop_column("services_history", "billing_reference")
    op.drop_column("services_history", "billing_contact_names")
    op.drop_column("services_history", "billing_contact_email_addresses")
    op.drop_column("services", "purchase_order_number")
    op.drop_column("services", "billing_reference")
    op.drop_column("services", "billing_contact_names")
    op.drop_column("services", "billing_contact_email_addresses")
    # ### end Alembic commands ###
