"""

Revision ID: 0340_stub_training_broadcasts
Revises: 0339_service_billing_details
Create Date: 2021-01-26 16:48:44.921065

"""

import sqlalchemy as sa
from alembic import op

revision = "0340_stub_training_broadcasts"
down_revision = "0339_service_billing_details"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("broadcast_message", sa.Column("stubbed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broadcast_message", "stubbed")
    # ### end Alembic commands ###
