"""

Revision ID: 0344_stubbed_not_nullable
Revises: 0343_org_billing_details
Create Date: 2021-02-08 18:10:15.533279

"""

import sqlalchemy as sa
from alembic import op

revision = "0344_stubbed_not_nullable"
down_revision = "0343_org_billing_details"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE broadcast_message SET stubbed = False WHERE stubbed is null")
    op.alter_column("broadcast_message", "stubbed", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("broadcast_message", "stubbed", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
