"""

Revision ID: 0398_active_email_branding
Revises: 0397_drop_research_mode
Create Date: 2023-01-12 16:45:46.505237

"""

import sqlalchemy as sa
from alembic import op

revision = "0398_active_email_branding"
down_revision = "0397_drop_research_mode"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("email_branding", sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_branding", "active")
    # ### end Alembic commands ###
