"""

Revision ID: 0419_take_part_in_research
Revises: 0418_readd_null_constraint
Create Date: 2023-07-05 12:31:03.540011

"""

from alembic import op
import sqlalchemy as sa


revision = "0419_take_part_in_research"
down_revision = "0418_readd_null_constraint"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("take_part_in_research", sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "take_part_in_research")
    # ### end Alembic commands ###
