"""

Revision ID: 0421_bilingual_templates
Revises: 0420_unique_service_name_1
Create Date: 2023-08-30 17:26:28.925639

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0421_bilingual_templates"
down_revision = "0420_unique_service_name_1"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("letter_welsh_content", sa.Text(), nullable=True))
    op.add_column("templates", sa.Column("letter_welsh_subject", sa.Text(), nullable=True))
    letter_language_options = postgresql.ENUM(
        "english", "welsh_then_english", name="letter_language_options", create_type=False
    )
    letter_language_options.create(op.get_bind(), checkfirst=True)
    op.add_column("templates", sa.Column("letter_languages", letter_language_options, nullable=True))
    op.add_column("templates_history", sa.Column("letter_welsh_content", sa.Text(), nullable=True))
    op.add_column("templates_history", sa.Column("letter_welsh_subject", sa.Text(), nullable=True))
    op.add_column(
        "templates_history",
        sa.Column("letter_languages", letter_language_options, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates_history", "letter_languages")
    op.drop_column("templates_history", "letter_welsh_subject")
    op.drop_column("templates_history", "letter_welsh_content")
    op.drop_column("templates", "letter_languages")
    op.drop_column("templates", "letter_welsh_subject")
    op.drop_column("templates", "letter_welsh_content")
    sa.Enum(name="letter_language_options").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
