"""

Revision ID: 0422_letter_languages_constraint
Revises: 0421_bilingual_templates
Create Date: 2023-09-07 14:00:28.925639

"""

from alembic import op


revision = "0422_letter_languages_constraint"
down_revision = "0421_bilingual_templates"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE templates SET letter_languages = 'english' WHERE template_type = 'letter'
        """
    )
    op.execute(
        """
        UPDATE templates_history SET letter_languages = 'english' WHERE template_type = 'letter'
        """
    )

    op.execute(
        """
        ALTER TABLE templates ADD CONSTRAINT "chk_templates_letter_languages"
        CHECK (
            CASE WHEN template_type = 'letter' THEN
                letter_languages is not null
            ELSE
                letter_languages is null
            END
        )
        """
    )
    op.execute(
        """
        ALTER TABLE templates_history ADD CONSTRAINT "chk_templates_history_letter_languages"
        CHECK (
            CASE WHEN template_type = 'letter' THEN
                letter_languages is not null
            ELSE
                letter_languages is null
            END
        )
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE templates DROP CONSTRAINT "chk_templates_letter_languages"
        """
    )
    op.execute(
        """
        ALTER TABLE templates_history DROP CONSTRAINT "chk_templates_history_letter_languages"
        """
    )
    # ### end Alembic commands ###
