"""
Create Date: 2025-05-14 15:52:49.416158
"""

import textwrap
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

revision = '0502_non_nullable_subject'
down_revision = "0501_drop_inbound_api_table"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            UPDATE templates
            SET
                subject = 'filler subject',
                updated_at = now()
            WHERE
                subject IS null
            """
    )
    op.alter_column("templates", "subject", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("templates", "subject", nullable=True)
    # ### end Alembic commands ###
