"""
Create Date: 2025-10-14 14:03:08.750459
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0537_templates_email_files"
down_revision = "0536_inbound_sms_xstats_dep"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_email_files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('link_text', sa.Text(), nullable=True),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.Column('validate_users_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('archived_by_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_email_files_archived_by_id'), 'template_email_files', ['archived_by_id'], unique=False)
    op.create_index(op.f('ix_template_email_files_created_by_id'), 'template_email_files', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_template_email_files_template_id'), 'template_email_files', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_email_files_template_version'), 'template_email_files', ['template_version'], unique=False)
    op.create_table('template_email_files_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('link_text', sa.Text(), nullable=True),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.Column('validate_users_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('archived_by_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index(op.f('ix_template_email_files_history_archived_by_id'), 'template_email_files_history', ['archived_by_id'], unique=False)
    op.create_index(op.f('ix_template_email_files_history_created_by_id'), 'template_email_files_history', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_template_email_files_history_template_id'), 'template_email_files_history', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_email_files_history_template_version'), 'template_email_files_history', ['template_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_email_files_history_template_version'), table_name='template_email_files_history')
    op.drop_index(op.f('ix_template_email_files_history_template_id'), table_name='template_email_files_history')
    op.drop_index(op.f('ix_template_email_files_history_created_by_id'), table_name='template_email_files_history')
    op.drop_index(op.f('ix_template_email_files_history_archived_by_id'), table_name='template_email_files_history')
    op.drop_table('template_email_files_history')
    op.drop_index(op.f('ix_template_email_files_template_version'), table_name='template_email_files')
    op.drop_index(op.f('ix_template_email_files_template_id'), table_name='template_email_files')
    op.drop_index(op.f('ix_template_email_files_created_by_id'), table_name='template_email_files')
    op.drop_index(op.f('ix_template_email_files_archived_by_id'), table_name='template_email_files')
    op.drop_table('template_email_files')
    # ### end Alembic commands ###
