"""empty message

Revision ID: 6e1c9151b162
Revises: 0080_fix_rate_start_date
Create Date: 2017-05-08 09:44:10.474684

"""

# revision identifiers, used by Alembic.
revision = '6e1c9151b162'
down_revision = '0080_fix_rate_start_date'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_statistics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('service_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('emails_requested', sa.BigInteger(), nullable=False),
    sa.Column('emails_delivered', sa.BigInteger(), nullable=False),
    sa.Column('emails_failed', sa.BigInteger(), nullable=False),
    sa.Column('sms_billable_units', sa.BigInteger(), nullable=False),
    sa.Column('sms_requested', sa.BigInteger(), nullable=False),
    sa.Column('sms_delivered', sa.BigInteger(), nullable=False),
    sa.Column('sms_failed', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'day', name='uix_service_to_day')
    )
    op.create_index(op.f('ix_notification_statistics_day'), 'notification_statistics', ['day'], unique=False)
    op.create_index(op.f('ix_notification_statistics_service_id'), 'notification_statistics', ['service_id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_statistics_service_id'), table_name='notification_statistics')
    op.drop_index(op.f('ix_notification_statistics_day'), table_name='notification_statistics')
    op.drop_table('notification_statistics')
