#!/bin/bash
set -eu

DOCKER_IMAGE_NAME=notifications-api

source environment.sh

EXPOSED_PORTS="-e PORT=6011 -p 6011:6011"

docker run -d -it --rm \
  -e NOTIFY_ENVIRONMENT=$NOTIFY_ENVIRONMENT \
  -e MMG_API_KEY=$MMG_API_KEY \
  -e FIRETEXT_API_KEY=$FIRETEXT_API_KEY \
  -e NOTIFICATION_QUEUE_PREFIX=$NOTIFICATION_QUEUE_PREFIX \
  -e FLASK_APP=$FLASK_APP \
  -e FLASK_DEBUG=$FLASK_DEBUG \
  -e WERKZEUG_DEBUG_PIN=$WERKZEUG_DEBUG_PIN \
  ${EXPOSED_PORTS} \
  -v $(pwd):/home/vcap/app \
  ${DOCKER_IMAGE_NAME} \
  ${@}
