from app import db
from app.models.context import clear_model_context, set_model_context

set_model_context(db)

from .all_models import *

__all__ = [
    "User",
    "ServiceUser",
    "BrandingTypes",
    "EmailBranding",
    "LetterBranding",
    "ServicePermissionTypes",
    "Domain",
    "OrganisationTypes",
    "OrganisationPermission",
    "OrganisationUserPermissions",
    "Organisation",
    "OrganisationEmailBranding",
    "Service",
    "DefaultAnnualAllowance",
    "AnnualBilling",
    "InboundNumber",
    "ServiceSmsSender",
    "ServicePermission",
    "ServiceGuestList",
    "ServiceCallbackApi",
    "ServiceCallbackType",
    "ApiKey",
    "KeyTypes",
    "TemplateFolder",
    "TemplateBase",
    "Template",
    "TemplateRedacted",
    "TemplateHistory",
    "ProviderDetails",
    "ProviderDetailsHistory",
    "JobStatus",
    "Job",
    "VerifyCode",
    "NotificationStatusTypes",
    "NotificationAllTimeView",
    "Notification",
    "NotificationHistory",
    "LetterCostThreshold",
    "NotificationLetterDespatch",
    "InviteStatusType",
    "InvitedUser",
    "InvitedOrganisationUser",
    "Permission",
    "Event",
    "Rate",
    "InboundSms",
    "InboundSmsHistory",
    "LetterRate",
    "ServiceEmailReplyTo",
    "ServiceLetterContact",
    "AuthType",
    "FactBillingLetterDespatch",
    "FactBilling",
    "FactNotificationStatus",
    "FactProcessingTime",
    "Complaint",
    "ServiceDataRetention",
    "ReturnedLetter",
    "ServiceContactList",
    "WebauthnCredential",
    "LetterAttachment",
    "UnsubscribeRequestReport",
    "UnsubscribeRequest",
    "UnsubscribeRequestHistory",
    "ProtectedSenderId",
    "SerializedServiceJoinRequest",
    "ServiceJoinRequest",
    "SerializedReportRequest",
    "ReportRequest"
    ]
